fengyuanchen/cropperjs

src/js/methods.js
This fixes the `$ is not defined error` when getCanvasData is called.
This doesn't happen in the demo because jQuery is available.
=> remove jQuery reference in getCanvasData using existing each method

README.md
Similar to how the [cropper](https://github.com/fengyuanchen/cropper) repo has related projects, add [react-cropperjs](https://github.com/TAPP-TV/react-cropperjs) under the related projects section at the bottom of the README. Adding it to the related projects section increases the reach of the cropperjs project.
react-cropperjs wraps cropperjs and provides an interface to React apps wanting to utilize the cropper without a jQuery depedency.
=> Add related projects section

src/js/cropper.js, test/methods/replace.js
UI was not being refreshed by `crop()` after a `replace()` because `cropped` was not being reset to `false`.
`autoCrop` had worked okay because it doesn't care about `cropped`.
I hope the new test for `replace` is okay.
Fixes #83.
=> Fixed `replace()` without `autoCrop` crash

src/js/template.js
We use the popular [jquery/PEP](https://github.com/jquery/pep) as polyfill for the pointer events API. When using this API cropperjs does not respond anymore on touch devices that require this polyfill.
Normally the touch-action CSS property (used on cropper-container) will trigger the pointer events when the browser natively supports it. The polyfill cannot use this property easily since the browser does not actually support it, will throw it out and make it impossible to read it in the polyfill code. To resolve this many pointer event polyfills use a custom attribute (`touch-action=".."`) on the html element instead. If this attribute is not present, no pointer events are triggered (similar to the CSS property).
Because cropperjs switches to pointer events if the PointerEvent class is …
=> Touch-action attribute for pointer event polyfill compatibility

package.json
Please check if your PR fulfills the following requirements:
- n/a Tests for the changes have been added (for bug fixes / features)
- n/a Docs have been added / updated (for bug fixes / features)
What kind of change does this PR introduce?
```
[x] Bugfix
[ ] Feature
[ ] Refactor
[x] Build related changes
[ ] Other, Please describe:
```
Tools like webpack currently pick the bundle from the `browser` field over the bundles in `main` or `module`. This happens because including the `browser` field means that the `main` and `module` bundles are meant for use with Node, and the `browser` bundle is meant for use in browsers. See the [package browser field spec](https://github.com/defunctzombie/package-browser-field-spec). `cropperjs` does …
=> fix(package): remove browser field

types/index.d.ts
Please check if your PR fulfills the following requirements:
- n/a [ ] Tests for the changes have been added (for bug fixes / features)
- n/a  [ ] Docs have been added / updated (for bug fixes / features)
What kind of change does this PR introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Refactor
[ ] Build related changes
[x] Other, Please describe: Typescript definitions update
```
TypeScript definitions for zoomTo does not accept optional param pivot.
Issue Number: N/A
zoomTo now accepts optional param pivot.
```
[ ] Yes
[x] No
```
=> fix: TS definitions - Add missing pivot to zoomTo

src/js/render.js, test/specs/options/viewMode.spec.js
- [n/a] Docs have been added / updated (for bug fixes / features)
```
[x] Bugfix
[ ] Feature
[ ] Refactor
[ ] Build related changes
[ ] Other, Please describe:
```
When using "viewMode" 1 or 2, the crop box could overflow if the canvas is moved partly beyond the container boundaries.
If moved beyond the top/left boundaries, it could overflow the container. If moved beyond the bottom/right boundaries, it could overflow the canvas (exceeding its size).
This behavior can be reproduced on the demo page:
https://fengyuanchen.github.io/cropperjs/
Steps to reproduce:
1. In "viewMode" 1 or 2 drag mode, switch to using "free" aspect ratio
2. Drag the image beyond the top/left or bottom/right container boundaries
3. Use "setData" with …
=> fix: crop box overflows in "viewMode" 1 and 2

src/js/cropper.js
This change improves performance when a JPEG image is loaded from a
data url and checkOrientation is set to true. Before this change, the
image was converted into a byte array and then it was converted back
into a data url, without being modified between the two steps. After
this change, we will just reuse the original data url instead of
converting the byte array back. (This saves ~1secs on my laptop with
large photos.)
Please check if your PR fulfills the following requirements:
- [n.a.] Tests for the changes have been added (for bug fixes / features)
- [n.a.] Docs have been added / updated (for bug fixes / features)
What kind of change does this PR introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Refactor
[ ] Build related changes
[X] …
```
=> perf: don't recompute the DataUrl if it is already known

src/js/utilities.js
This change improves performance when a JPEG image is loaded from a
data url and `checkOrientation` is set to true. Before this change,
the `data` string was built by adding characters one by one. After
this change, the characers will be added in chunks.
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Refactor
[ ] Build related changes
[X] Other, Please describe: performance improvement
```
The behavior is unchanged.
Issue Number: N/A
The behavior is unchanged.
```
[ ] Yes
[X] No
```
Here is some example code that demonstrates the speedup:
```
// Generate test data.
var tmp = []; for (var i = 0; i < 8 * 1000 * 1000; ++i) tmp.push((i % 10) + 50); …
```
=> perf: add characters in chunks in dataURLToArrayBuffer

types/index.d.ts
**Summary**
The enums don't exist at runtime (as the source code does not have them as it is not TS). So declaring them as enum causes issues. I got tsc warnings when trying to run it to check the JS code. Passing `move` explicitly was not considered as a valid value for the `drag` option.
String enums are replaced with a union of literal types. The ViewMode is turned into a const enum so that typescript will inline the numbers during …
=> Fix the TS types for the drag mode, smoothing quality and view mode options

src/js/constants.js
Upgrading from 1.0.0-rc.3 to 1.5.0+ makes the page crashed: 
`TypeError: Cannot use 'in' operator to search for 'ontouchstart' in null`
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36 
The error points to this change:
https://github.com/fengyuanchen/cropperjs/commit/b78625f9ff4d5c2dd0dd34311f7c0e8d5211afaf#diff-6a721e8e6aa7d4dc81e0a3610e25ce44R3
**Summary**
If changing the UI of default theme, please provide the **before/after** screenshot:
You have tested in the …
=> fix: IS_TOUCH_DEVICE

types/index.d.ts
`preview` option needs to be a `NodeListOf<HTMLImageElement>`
**Summary**
If changing the UI of default theme, please provide the **before/after** screenshot:
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.
testcase: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAYShMYCmU4DNkjgcgGNlUMArAZ3wG4A …
=> Update in index.d.ts: preview option

types/index.d.ts
**Summary**
If changing the UI of default theme, please provide the **before/after** screenshot:
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.
=> fix: typescript typing

test/specs/options/wheelZoomRatio.spec.js
**Summary**
If changing the UI of default theme, please provide the **before/after** screenshot:
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.
Wanted to play with the lib and to check some ideas. Simple `npm run test` on `master` failed on me in minor way and for obscure reason. Seems like something …
=> test: make `wheelZoomRatio` test check less strict (round up to tenths)

docs/examples/crop-a-round-image.html
Because of an old [bug](https://bugs.webkit.org/show_bug.cgi?id=20807) the css styles for `outline` do not follow `border-radius` on iOS/Safari. The example "crop-a-round-image.html" would show a rectangular crop box in browsers with this bug.
I fixed it, following the approach that is also suggested in issue [#545](https://github.com/fengyuanchen/cropper/issues/545). …
=> fix: example for round image on iOS/Safari

README.md, src/js/methods.js, types/index.d.ts
**Summary**
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.
=> fix: add `rounded` option to the `getCroppedCanvas` method (#551)

packages/cropperjs/src/index.ts
Allowing client to referrence/import the default template and maybe make modifications and feed to `template` param.
Currently the client have no way no know(?) what is the default template if leave undefined.
Not yet tested but is only an export statement. (Sorry didn't have time + no document to setup development on v2)
**Summary**
If adding a **new feature**, the …
=> feat(cropperjs): exports `DEFAULT_TEMPLATE`

docs/css/cropper.css
**Summary**
On iOS Chrome, after long-pressing on the cropper container area which makes the context menu pop up, only the pan gesture can be recognized, and other gestures don't work. And the pan gesture now only scales the image instead of moving it like it was. You can see it in the video below.
https://github.com/fengyuanchen/cropperjs/assets/46563912/b84279f5-b01c-4620-9343-4715fd5dacad
Right now, the solution we found is adding "-webkit-touch-callout: none;" to the ".cropper-container" class selector.
If you'd like to apply this change, please review my pull request and merge it if there are no problems. Thanks!
**Does this PR …
=> iOS Chrome: Long press on .cropper-container triggers unexpected behavior

src/js/constants.js
**Summary**
Regexs like `/^a|b|c$/` match `a` at start of text, `c` at end of text, or `b`.  I assume this does not match the original intent.
This moves the union into a capture group so `^` and `$` are respected for the whole union and not just a couple members of the union.
To avoid wasting your time, it's …
=> fix: regex expressions - anchors not being respected

packages/element-shade/src/index.ts
**Summary**
As complained by [Issue #1078](https://github.com/fengyuanchen/cropperjs/issues/1078), the shade has a glitching offset effect if using the method to restrain the selection pointed out in the documentation. This change aims to eliminate that by directly tying the shade to the selection instead of the change event.
If adding a **new feature**, the PR's …
=> fix #1078 Prevent shade from "glitching" when pulling selection too far

packages/cropperjs/src/index.ts, packages/cropperjs/tests/index.spec.ts
New image element does the cross origin call to avoid canvas being tainted
**Summary**
The crossorigin attribute of the passing image will be passed through the underlying cropper-image element. Before, the image request would not use cors mode while it will now.
To avoid wasting your time, it's best to open a …
=> fix: set crossorigin attribute on cropper image element

packages/cropperjs/package.json
**Summary**
Part of a project I'm working on calls `require.resolve('cropperjs')` to retrieve the path of CropperJS. It does the same for the other Node modules in my project. 
However, the CropperJS `package.json` `require.node.default` link points to `./cropper.raw.js`, which does not exist. 
https://github.com/fengyuanchen/cropperjs/blob/91d5ab3b3637a20d710eeeab6d6353ce0db4a85f/packages/cropperjs/package.json#L24-L32
As a result, calling `require.resolve('cropperjs')` throws an error:
Changing this to `./dist/cropper.raw.js` fixes the issue. 
Moreover, I have added `"./package.json": "./package.json"` to the `package.json` `exports` to ensure that `require('cropperjs/package.json')` will resolve correctly, making CropperJS's metadata (version, author, license, etc.) more explicitly …
=> fix: correct require.node.default export and explicitly export package.json
